swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  title: "My API documentation Place"
  version: "1.0"
consumes:
  - application/json
produces:
  - application/json
basePath: /v1
tags:
- name: Places
  description: "Everything about your Places"
paths:
  /places:
      get:
        tags: 
        - Places
        operationId: place.views.views.read_place
        summary: Get all Places
        responses:
          200:
            description: 'get places'
            schema:
                type: array
                items:
                    $ref: '#/definitions/Place'
      post:
        tags: 
        - Places
        operationId: place.views.views.create_place
        summary: Create a character
        description: Create a new character
        parameters:
        - in: body
          name: place 
          description: Place to create
          required: true
          schema:
            $ref: '#/definitions/Place'
        responses:
            201:
               description: Successfully created character
               schema:
                    $ref: '#/definitions/Place'
            400:
               description: "Invalid input"
            409:
               description: "Character exist"
  /places/{place_id}:
    get:
      operationId: place.views.views.read_one
      tags: 
      - Places
      summary: Read one character
      description: Read one character
      parameters:
      - name: place_id
        in: path
        description: Id of the character to get
        type: integer
        required: True
      responses:
        200:
          description: Successfully read character from character data operation
          schema:
            $ref: '#/definitions/Place'
    put:
      operationId: place.views.views.update
      tags: 
      - Places
      summary: Update a character
      description: Update a character
      parameters:
      - name: place_id
        in: path
        description: Id the character to update
        type: integer
        required: True
      - name: place
        in: body
        schema:
            $ref: '#/definitions/Place'
      responses:
        200:
          description: Successfully updated character
          schema:
            $ref: '#/definitions/Place'
        400:
          description: "Invalid input"             
    delete:
      operationId: place.views.views.delete
      tags:
       - Places
      summary: Delete a character from the character list
      description: Delete a character
      parameters:
      - name: place_id
        in: path
        type: integer
        description: Id of the character to delete
        required: true
      responses:
        200:
          description: Successfully deleted a character

definitions:
  Place:
    type: object
    required:
    - name
    properties:  
      id:
        type: integer
      name:
        type: string
    example:
        id: 1
        name: Nombre lugar
