pyms:
  requests: true
  swagger:
    path: "swagger"
    file: "swagger.yml"
msplace:
  DEBUG: false
  TESTING: false
  APP_NAME: MicroservicePlace
  APPLICATION_ROOT : "/place"
  SQLALCHEMY_TRACK_MODIFICATIONS: true
  DATABASE: db.postgresql
  SQLALCHEMY_DATABASE_URI: postgresql://postgres:killer45@localhost/Prueba